### ISSUE TITLE
Design Journey Planner page

### ISSUE THREAD

**Issue by iamriya** [SAITARUN55/metroapp#19]
![WhatsApp Image 2020-03-23 at 1 26 25 AM](https://user-images.githubusercontent.com/42533173/77259247-3c48db00-6ca6-11ea-930e-c0025620a4aa.jpeg)
This is a rough idea for Journey planner page. A list of options available for the journey (for selected mode of transport) would be displayed, gesture for whom would navigate to the page with intermediate stations.
Parameters: Bus/Train number, Fare, Arrival time, Reach time.

**Comment by shilpi1958** [comment]
Journey planner mockup.

- In accordance with the idea of using different colors for different metro lines. 
- Since the frequency of trains is an essential consideration while we plan our journey it is highlighted. 
- The same platform can have trains moving in different directions, hence outbound stations specified.

![Journey planner](https://user-images.githubusercontent.com/26502870/77794916-b6a4a100-7092-11ea-9718-1f7bf06c8e8c.png)
